# SwiftLint Configuration for AbacusKit
# Swift 6 / iOS 17+ / Clean Architecture

# Paths
included:
  - Sources
  - Tests

excluded:
  - .build
  - .swiftpm
  - Sources/AbacusKitBridge
  - Tests/AbacusKitTests/Generated

# Rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - unused_declaration
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

disabled_rules:
  - todo
  - line_length
  - type_body_length
  - file_length
  - function_body_length
  - cyclomatic_complexity
  - force_cast
  - force_try
  - nesting

# Rule Configurations
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - url
    - URL
    - db
    - to
    - x
    - y
    - z

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 60

function_parameter_count:
  warning: 6
  error: 8

large_tuple:
  warning: 3
  error: 4

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true

vertical_whitespace:
  max_empty_lines: 2

# Custom Rules
custom_rules:
  no_print:
    name: "No Print Statements"
    regex: '(?<!//)\bprint\('
    message: "Use Logger instead of print()"
    severity: warning

  no_nslog:
    name: "No NSLog"
    regex: '\bNSLog\('
    message: "Use Logger instead of NSLog()"
    severity: warning

# Reporter
reporter: "xcode"
